# Generated by Django 5.1.7 on 2025-04-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coverplateconnection_endplateconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeamToColumnEndPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beam_size', models.CharField(max_length=100)),
                ('column_size', models.CharField(max_length=100)),
                ('plate_thickness', models.FloatField()),
                ('bolt_diameter', models.FloatField()),
                ('bolt_grade', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CoverPlateConnection',
        ),
        migrations.DeleteModel(
            name='EndPlateConnection',
        ),
        migrations.DeleteModel(
            name='ShearConnection',
        ),
    ]
