# Generated by Django 5.1.7 on 2025-04-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='parent_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navigationitem',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
