# Generated by Django 5.1.7 on 2025-04-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_navigationitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
